### ISSUE TITLE
Can't run the platform on `main` branch

### ISSUE THREAD

**Issue by wardru** [Panduza/panduza-rust-platform#15]
After running `cargo run --features trac-fmt`, it crashes with the following errors:

Ubuntu 24.04 LTS
cargo 1.75.0

```
thread 'main' panicked at src/log/platform_formatter.rs:123:56:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/log/platform_formatter.rs:123:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
thread 'tokio-runtime-worker' panicked at src/log/platform_formatter.rs:123:56:
called `Option::unwrap()` on a `None` value
   0:     0x5c58eba8164b - std::backtrace_rs::backtrace::libunwind::trace::he991e66e5f22a1db
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5c58eba8164b - std::backtrace_rs::backtrace::trace_unsynchronized::h43f35a5576eecb13
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5c58eba8164b - std::sys_common::backtrace::_print_fmt::hf9c799a68b2477fc
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5c58eba8164b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2d48dfeb5948660
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5c58ebab6a70 - core::fmt::rt::Argument::fmt::h507ca91fbb1ef494
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/rt.rs:142:9
   5:     0x5c58ebab6a70 - core::fmt::write::h4d5f6025aa566322
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1120:17
   6:     0x5c58eba768ad - std::io::Write::write_fmt::hc088b3c8cc6dcb9f
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1762:15
   7:     0x5c58eba81434 - std::sys_common::backtrace::_print::h231201f6cff8f56a
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5c58eba81434 - std::sys_common::backtrace::print::h478d6be486f8cd2d
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5c58eba9fb7a - std::panicking::default_hook::{{closure}}::hf1c55106b4d45a90
  10:     0x5c58eba9f81d - std::panicking::default_hook::h7b29000c631cc719
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:292:9
  11:     0x5c58eba9ff98 - std::panicking::rust_panic_with_hook::h2a988919dd121561
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:779:13
  12:     0x5c58eba819f9 - std::panicking::begin_panic_handler::{{closure}}::h3a9eaa1d23ecf555
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:649:13
  13:     0x5c58eba81866 - std::sys_common::backtrace::__rust_end_short_backtrace::h813561fdec15f700
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5c58eba9fcc2 - rust_begin_unwind
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:645:5
  15:     0x5c58eb2afdf5 - core::panicking::panic_fmt::hef0307862026e6f9
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:72:14
  16:     0x5c58eb2afe93 - core::panicking::panic::hf516d800ede7db8c
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:127:5
  17:     0x5c58eb379bf0 - core::option::Option<T>::unwrap::h6ed2b4425b1b055b
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/option.rs:931:21
  18:     0x5c58eb32125e - <panduza_rust_platform::log::platform_formatter::PlatformFormatter as tracing_subscriber::fmt::format::FormatEvent<S,N>>::format_event::hb988fad75ba7a36f
                               at /home/agouby/panduza-rust-platform/src/log/platform_formatter.rs:123:23
  19:     0x5c58eb326b67 - <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event::{{closure}}::h9b9858fcd8df5c0d
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/fmt_layer.rs:965:16
  20:     0x5c58eb3bf8d4 - std::thread::local::LocalKey<T>::try_with::h8e534f0e89114375
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/thread/local.rs:270:16
  21:     0x5c58eb3beb3a - std::thread::local::LocalKey<T>::with::heacbdc9294cace62
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/thread/local.rs:246:9
  22:     0x5c58eb326927 - <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event::h6ef8640b816623b1
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/fmt_layer.rs:949:9
  23:     0x5c58eb37b2f2 - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::event::hc1a641a693412e47
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/layer/layered.rs:153:9
  24:     0x5c58eb37b270 - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::event::h04c61b23ce38ba44
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/layer/layered.rs:152:9
  25:     0x5c58eb3abb13 - <tracing_subscriber::fmt::Subscriber<N,E,F,W> as tracing_core::subscriber::Subscriber>::event::h3c53fed49eab9826
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/mod.rs:408:9
  26:     0x5c58eba72695 - tracing_core::dispatcher::Dispatch::event::ha8e199a0b21560cf
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/dispatcher.rs:615:13
  27:     0x5c58eba66601 - tracing_core::event::Event::dispatch::{{closure}}::h98edcfc4131b2a77
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/event.rs:35:13
  28:     0x5c58eba71df7 - tracing_core::dispatcher::get_default::h03fe53f684dd9dec
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/dispatcher.rs:391:16
  29:     0x5c58eba665cf - tracing_core::event::Event::dispatch::h0796496520c0d60f
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/event.rs:34:9
  30:     0x5c58eb679a19 - <tokio::sync::oneshot::Receiver<T> as core::future::future::Future>::poll::{{closure}}::h0ec539175f5b9f67
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/macros.rs:875:17
  31:     0x5c58eb678ebc - <tokio::sync::oneshot::Receiver<T> as core::future::future::Future>::poll::hc6286da57fda8d51
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/sync/oneshot.rs:1102:30
  32:     0x5c58eb66eeee - <&mut F as core::future::future::Future>::poll::h26b7b983752fe65d
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/future/future.rs:113:9
  33:     0x5c58eb671e26 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h9a02ad15f8a72b48
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:63
  34:     0x5c58eb671c9f - tokio::runtime::coop::with_budget::h0c422afb55f2978c
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107:5
  35:     0x5c58eb671c9f - tokio::runtime::coop::budget::hf8e95b7d3a42585b
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73:5
  36:     0x5c58eb671c9f - tokio::runtime::park::CachedParkThread::block_on::hdae855da97840bc3
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281:31
  37:     0x5c58eb672089 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h668c85ba7c8a767b
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/blocking.rs:66:9
  38:     0x5c58eb6daadf - tokio::runtime::blocking::shutdown::Receiver::wait::hf0484b49fda4da72
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/shutdown.rs:67:21
  39:     0x5c58eb690464 - tokio::runtime::blocking::pool::BlockingPool::shutdown::hf561bda1d643ce96
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:261:12
  40:     0x5c58eb69084e - <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop::h8bdb0a4fc3991cc7
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:278:9
  41:     0x5c58eb61a197 - core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>::h8efe70d286d8e66a
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ptr/mod.rs:498:1
  42:     0x5c58eb619524 - core::ptr::drop_in_place<tokio::runtime::runtime::Runtime>::h5aaa842a82342e36
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ptr/mod.rs:498:1
  43:     0x5c58eb2b33f2 - panduza_rust_platform::main::h38adf252dbb3b17e
                               at /home/agouby/panduza-rust-platform/src/main.rs:21:56
  44:     0x5c58eb2be52b - core::ops::function::FnOnce::call_once::h0209c8de881b99ef
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ops/function.rs:250:5
  45:     0x5c58eb2bc3ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h79b8e4316a87d8cb
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:154:18
  46:     0x5c58eb3a3c41 - std::rt::lang_start::{{closure}}::h54585200cf992a13
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:167:18
  47:     0x5c58eba9fbb4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2a98286140a8c485
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ops/function.rs:284:13
  48:     0x5c58eba9fbb4 - std::panicking::try::do_call::h6f884a82d660d639
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:552:40
  49:     0x5c58eba9fbb4 - std::panicking::try::h3d219ee83761ccf8
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:516:19
  50:     0x5c58eba9fbb4 - std::panic::catch_unwind::h0a8f78f1f5633cdb
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panic.rs:142:14
  51:     0x5c58eba9fbb4 - std::rt::lang_start_internal::{{closure}}::hd36869a5192571c4
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:148:48
  52:     0x5c58eba9fbb4 - std::panicking::try::do_call::hbfe6916f1cc74e35
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:552:40
  53:     0x5c58eba9fbb4 - std::panicking::try::h0cc643a8ace88736
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:516:19
  54:     0x5c58eba8c5cb - std::panic::catch_unwind::hd66d6c526b1a6302
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panic.rs:142:14
  55:     0x5c58eba8c5cb - std::rt::lang_start_internal::h8fc8e9636333b06e
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:148:20
  56:     0x5c58eb3a3c1a - std::rt::lang_start::hb20ed9a2093bf13c
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:166:17
  57:     0x5c58eb2b348e - main
  58:     0x7b2123e2a1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  59:     0x7b2123e2a28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  60:     0x5c58eb2b0815 - _start
  61:                0x0 - <unknown>
thread 'main' panicked at src/log/platform_formatter.rs:123:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x5c58eba8164b - std::backtrace_rs::backtrace::libunwind::trace::he991e66e5f22a1db
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5c58eba8164b - std::backtrace_rs::backtrace::trace_unsynchronized::h43f35a5576eecb13
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5c58eba8164b - std::sys_common::backtrace::_print_fmt::hf9c799a68b2477fc
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5c58eba8164b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2d48dfeb5948660
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5c58ebab6a70 - core::fmt::rt::Argument::fmt::h507ca91fbb1ef494
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/rt.rs:142:9
   5:     0x5c58ebab6a70 - core::fmt::write::h4d5f6025aa566322
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1120:17
   6:     0x5c58eba768ad - std::io::Write::write_fmt::hc088b3c8cc6dcb9f
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1762:15
   7:     0x5c58eba81434 - std::sys_common::backtrace::_print::h231201f6cff8f56a
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5c58eba81434 - std::sys_common::backtrace::print::h478d6be486f8cd2d
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5c58eba9fb7a - std::panicking::default_hook::{{closure}}::hf1c55106b4d45a90
  10:     0x5c58eba9f81d - std::panicking::default_hook::h7b29000c631cc719
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:292:9
  11:     0x5c58eba9ff98 - std::panicking::rust_panic_with_hook::h2a988919dd121561
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:779:13
  12:     0x5c58eba819f9 - std::panicking::begin_panic_handler::{{closure}}::h3a9eaa1d23ecf555
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:649:13
  13:     0x5c58eba81866 - std::sys_common::backtrace::__rust_end_short_backtrace::h813561fdec15f700
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5c58eba9fcc2 - rust_begin_unwind
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:645:5
  15:     0x5c58eb2afdf5 - core::panicking::panic_fmt::hef0307862026e6f9
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:72:14
  16:     0x5c58eb2afe93 - core::panicking::panic::hf516d800ede7db8c
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:127:5
  17:     0x5c58eb379bf0 - core::option::Option<T>::unwrap::h6ed2b4425b1b055b
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/option.rs:931:21
  18:     0x5c58eb32125e - <panduza_rust_platform::log::platform_formatter::PlatformFormatter as tracing_subscriber::fmt::format::FormatEvent<S,N>>::format_event::hb988fad75ba7a36f
                               at /home/agouby/panduza-rust-platform/src/log/platform_formatter.rs:123:23
  19:     0x5c58eb326b67 - <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event::{{closure}}::h9b9858fcd8df5c0d
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/fmt_layer.rs:965:16
  20:     0x5c58eb3bf8d4 - std::thread::local::LocalKey<T>::try_with::h8e534f0e89114375
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/thread/local.rs:270:16
  21:     0x5c58eb3beb3a - std::thread::local::LocalKey<T>::with::heacbdc9294cace62
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/thread/local.rs:246:9
  22:     0x5c58eb326927 - <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event::h6ef8640b816623b1
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/fmt_layer.rs:949:9
  23:     0x5c58eb37b2f2 - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::event::hc1a641a693412e47
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/layer/layered.rs:153:9
  24:     0x5c58eb37b270 - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::event::h04c61b23ce38ba44
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/layer/layered.rs:152:9
  25:     0x5c58eb3abb13 - <tracing_subscriber::fmt::Subscriber<N,E,F,W> as tracing_core::subscriber::Subscriber>::event::h3c53fed49eab9826
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/mod.rs:408:9
  26:     0x5c58eba72695 - tracing_core::dispatcher::Dispatch::event::ha8e199a0b21560cf
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/dispatcher.rs:615:13
  27:     0x5c58eba66601 - tracing_core::event::Event::dispatch::{{closure}}::h98edcfc4131b2a77
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/event.rs:35:13
  28:     0x5c58eba71df7 - tracing_core::dispatcher::get_default::h03fe53f684dd9dec
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/dispatcher.rs:391:16
  29:     0x5c58eba665cf - tracing_core::event::Event::dispatch::h0796496520c0d60f
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/event.rs:34:9
  30:     0x5c58eb6799b9 - <tokio::sync::oneshot::Receiver<T> as core::ops::drop::Drop>::drop::{{closure}}::{{closure}}::h493f7bb80fe82b6d
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/macros.rs:875:17
  31:     0x5c58eb677aee - <tokio::sync::oneshot::Receiver<T> as core::ops::drop::Drop>::drop::{{closure}}::hcadada6668184d8d
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/sync/oneshot.rs:1078:17
  32:     0x5c58eb658ffd - tracing::span::Span::in_scope::hd2b84c1d766caa90
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:1102:9
  33:     0x5c58eb67761b - <tokio::sync::oneshot::Receiver<T> as core::ops::drop::Drop>::drop::h4de0e394f6eb80b8
                               at /home/agouby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/sync/oneshot.rs:1077:13
  34:     0x5c58eb61a5f7 - core::ptr::drop_in_place<tokio::sync::oneshot::Receiver<()>>::h934e5ffe49c272a4
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ptr/mod.rs:498:1
  35:     0x5c58eb61a22b - core::ptr::drop_in_place<tokio::runtime::blocking::shutdown::Receiver>::h0187c498246fb4ed
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ptr/mod.rs:498:1
  36:     0x5c58eb61a1df - core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>::h8efe70d286d8e66a
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ptr/mod.rs:498:1
  37:     0x5c58eb619524 - core::ptr::drop_in_place<tokio::runtime::runtime::Runtime>::h5aaa842a82342e36
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ptr/mod.rs:498:1
  38:     0x5c58eb2b33f2 - panduza_rust_platform::main::h38adf252dbb3b17e
                               at /home/agouby/panduza-rust-platform/src/main.rs:21:56
  39:     0x5c58eb2be52b - core::ops::function::FnOnce::call_once::h0209c8de881b99ef
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ops/function.rs:250:5
  40:     0x5c58eb2bc3ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h79b8e4316a87d8cb
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:154:18
  41:     0x5c58eb3a3c41 - std::rt::lang_start::{{closure}}::h54585200cf992a13
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:167:18
  42:     0x5c58eba9fbb4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2a98286140a8c485
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ops/function.rs:284:13
  43:     0x5c58eba9fbb4 - std::panicking::try::do_call::h6f884a82d660d639
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:552:40
  44:     0x5c58eba9fbb4 - std::panicking::try::h3d219ee83761ccf8
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:516:19
  45:     0x5c58eba9fbb4 - std::panic::catch_unwind::h0a8f78f1f5633cdb
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panic.rs:142:14
  46:     0x5c58eba9fbb4 - std::rt::lang_start_internal::{{closure}}::hd36869a5192571c4
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:148:48
  47:     0x5c58eba9fbb4 - std::panicking::try::do_call::hbfe6916f1cc74e35
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:552:40
  48:     0x5c58eba9fbb4 - std::panicking::try::h0cc643a8ace88736
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:516:19
  49:     0x5c58eba8c5cb - std::panic::catch_unwind::hd66d6c526b1a6302
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panic.rs:142:14
  50:     0x5c58eba8c5cb - std::rt::lang_start_internal::h8fc8e9636333b06e
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:148:20
  51:     0x5c58eb3a3c1a - std::rt::lang_start::hb20ed9a2093bf13c
                               at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:166:17
  52:     0x5c58eb2b348e - main
  53:     0x7b2123e2a1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  54:     0x7b2123e2a28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  55:     0x5c58eb2b0815 - _start
  56:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:144:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
```

**Comment by wardru** [comment]
Fixed!
