### ISSUE TITLE
Platform stop working on xavier_chill_v2 when sending too many read request ?

### ISSUE THREAD

**Issue by Rethusan** [Panduza/panduza-rust-platform#193]
```
[memory_map_2] WARN: No sub task anymore
[memory_map_3] New command MemoryCommandCodec { mode: Read, address: 21, size: None, values: None, repeat_ms: None }
thread 'tokio-runtime-worker' panicked at plugins\fake\src\register_map\device.rs:46:25:
attempt to add with overflow
Join failed: task 34 panicked
[memory_map_3] WARN: No sub task anymore
[memory_map_4] New command MemoryCommandCodec { mode: Read, address: 21, size: None, values: None, repeat_ms: None }
thread 'tokio-runtime-worker' panicked at plugins\fake\src\register_map\device.rs:46:25:
attempt to add with overflow
Join failed: task 35 panicked
[memory_map_4] WARN: No sub task anymore
[memory_map_5] New command MemoryCommandCodec { mode: Read, address: 4, size: None, values: None, repeat_ms: None }
thread 'tokio-runtime-worker' panicked at plugins\fake\src\register_map\device.rs:46:25:
attempt to add with overflow
Join failed: task 36 panicked
[memory_map_5] WARN: No sub task anymore
[memory_map_0] New command MemoryCommandCodec { mode: Read, address: 15, size: None, values: None, repeat_ms: None }
thread 'tokio-runtime-worker' panicked at plugins\fake\src\register_map\device.rs:46:25:
attempt to add with overflow
Join failed: task 31 panicked
[memory_map_0] WARN: No sub task anymore
[memory_map_1] New command MemoryCommandCodec { mode: Read, address: 1, size: None, values: None, repeat_ms: None }
thread 'tokio-runtime-worker' panicked at plugins\fake\src\register_map\device.rs:46:25:
attempt to add with overflow
Join failed: task 32 panicked
[memory_map_1] WARN: No sub task anymore
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
Attribute not found
```

**Comment by XdoctorwhoZ** [comment]
@Rethusan si tu n'as plus le probléme peux tu fermer l'issue ? merci
