### ISSUE TITLE
Issues on v4.0.2

### ISSUE THREAD

**Issue by wardru** [Panduza/panduza-rust-platform#199]
I have two main issues with with 0.4.2

# Compile fail without `built-in-drivers` feature
```
error[E0425]: cannot find function `plugin_scanners` in module `built_in`
   --> src/platform.rs:604:34
    |
604 |         for scanner in built_in::plugin_scanners() {
    |                                  ^^^^^^^^^^^^^^^ not found in `built_in`
    |

```

# Platform crash
When the platform is compiled with builtins, it crashes if a plugin is also already installed in the plugin location.

```
thread 'main' panicked at src/platform.rs:436:51:
called `Result::unwrap()` on an `Err` value: PluginError("Unable to load plugin_entry_point [\"/etc/panduza/plugins/libpza_plugin_korad.so\"] - (DlSym { desc: \"/etc/panduza/plugins/libpza_plugin_korad.so: undefined symbol: plugin_entry_point\" })")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# KA3005P delay and structure

There is a delay when the a command is issued to the KA3005P, ~2 seconds.

Also the structure is mounted multiple times at connection, the first structure published contains only `identify`.
This messes up with the app because I don't expect structure to be published multiple times at connection.

**Comment by XdoctorwhoZ** [comment]
Can you test again with the 0.5.0 ? tell me if you have the issue.

**Comment by wardru** [comment]
```
[ 14:22 ][~/panduza/panduza-rust-platform]$ cargo run 
    Updating crates.io index
    Updating git repository `https://github.com/Panduza/panduza-platform-core`
    Updating git repository `https://github.com/Panduza/pza-plugin-fakes`
    Updating git repository `https://github.com/Panduza/pza-plugin-hameg`
    Updating git repository `https://github.com/Panduza/pza-plugin-korad`
    Updating git repository `https://github.com/Panduza/rumqtt`
error: failed to get `rumqttd` as a dependency of package `panduza-rust-platform v0.5.0 (/home/agouby/panduza/panduza-rust-platform)`

Caused by:
  failed to load source for dependency `rumqttd`

Caused by:
  Unable to update https://github.com/Panduza/rumqtt?tag=0.0.0

Caused by:
  failed to parse manifest at `/home/agouby/.cargo/git/checkouts/rumqtt-23e63b9f9424b28b/6e7d3f6/benchmarks/simplerouter/Cargo.toml`

Caused by:
  invalid type: map, expected a string for key `package.edition`

```

**Comment by wardru** [comment]
I still have the platform crash if the plugin `pza-plugin-korad` built on version `1.0.4` (same as the builtin), is deployed in the plugins folder and I start the platform with `cargo run -- -ld`

**Comment by wardru** [comment]
Also when running `cargo run --features built-in-drivers -- -ld ` if a plugin file is in the plugin folder

```
[ 14:46 ][~/panduza/panduza-rust-platform]$ cargo run --features built-in-drivers -- -ld 
warning: unused variable: `result`
   --> src/platform.rs:619:17
    |
619 |             let result = scanner.scan();
    |                 ^^^^^^ help: if this is intentional, prefix it with an underscore: `_result`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `panduza-rust-platform` (bin "panduza-rust-platform") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/panduza-rust-platform -ld`
----------------------------------------
# Panduza Platform

- Stdout logs         : ENABLED
- Broker logs         : DISABLED
- Debug logs          : ENABLED
- Trace logs          : DISABLED

- Log dir             : "/etc/panduza/logs"
- Tree file           : "/etc/panduza/tree.json"
----------------------------------------
[P] -- Platform Start --
[P] Args: Args { log_stdout_enable: true, broker_log_enable: false, debug_log: true, trace_log: false }
[P] Platform Version: 0.5.0
[P] Rustc Version: rustc 1.83.0 (90b35a623 2024-11-26)
[P] All tasks completed
[P] Wait for new tasks
[P] ----- SERVICE : BOOT -----
[P] ----- SERVICE : START BROKER -----
[P] Start Broker
[P] All tasks completed
[P] Wait for new tasks
[P] ----- SERVICE : LOAD PLUGINS -----
[P] ? SEARCH PUGINS in (/home/agouby/panduza/panduza-rust-platform/target/debug/plugins)
[P] ? SEARCH PUGINS in (/etc/panduza/plugins)
[P] !  Found PUGIN file: "/etc/panduza/plugins/libpza_plugin_korad.so"
thread 'main' panicked at src/platform.rs:449:51:
called `Result::unwrap()` on an `Err` value: PluginError("Unable to load plugin_entry_point [\"/etc/panduza/plugins/libpza_plugin_korad.so\"] - (DlSym { desc: \"/etc/panduza/plugins/libpza_plugin_korad.so: undefined symbol: plugin_entry_point\" })")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
